config/routes.rb
Rails.application.routes.draw do
  # resources :klasses
  resources :games
  devise_for :users

  
  root to: 'welcome#index'

  # USER GAMES
  get '/my-games', to: 'games#user_games', as: 'user_games'
  get '/my-games/edit', to: 'games#edit_user_games', as: 'edit_user_games'
  patch '/my-games/edit', to: 'games#update_user_games', as: 'update_user_games'

  # GAME CLASSES
  get '/:slug/classes', to: 'klasses#index', as: 'game_classes'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :user_games
  has_many :users, through: :user_games
  has_many :klasses

  before_destroy :destroy_user_games

  def slug
    self.name.gsub(" ", "-")
  end

  def self.find_by_slug(slug)
    self.all.find{|obj| obj.slug == slug}
  end

  private

    def destroy_user_games
      self.user_games.destroy_all
    end
end

app/models/klass.rb
class Klass < ApplicationRecord
  belongs_to :game

  def self.tanks
    where('role = ?', "Tank")
  end
  def self.healers
    where('role = ?', "Healer")
  end
  def self.melee
    where('role = ?', "Melee")
  end
  def self.ranged
    where('role = ?', "Ranged")
  end
  def self.casters
    where('role = ?', "Caster")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_games
  has_many :games, through: :user_games

  before_destroy :destroy_user_games

  private

    def destroy_user_games
      self.user_games.destroy_all
    end
end

app/models/user_game.rb
class UserGame < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
  end

  def user_games
    @games = current_user.games
  end

  def edit_user_games
    @games = current_user.games
  end

  def update_user_games
    if !params[:user]
      current_user.update(game_ids: [])
      return redirect_to user_games_path
    end

    if current_user.update(user_game_params)
      flash[:alert] = "Successfully added games"
      redirect_to user_games_path
    else
      flash[:error] = current_user.errors.full_messages
      render :edit_user_games
    end
  end

  private

    def user_game_params
      params.require(:user).permit(:game_ids => [])
    end
end

app/controllers/klasses_controller.rb
class KlassesController < ApplicationController
  before_action :set_game, only: [:index]
  
  def index
    @classes = Klass.all
  end

  private
    def set_game
      @game = Game.find_by_slug(params[:slug]) if params[:slug]
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" unless devise_error_messages?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation" class="card red white-text">
      <div class="card-content">
        <span class="card-title">#{sentence}</span>
        <ul>#{messages}</ul>
      </div>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    !resource.errors.empty?
  end

end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/klasses_helper.rb
module KlassesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/games/edit_user_games.html.erb
<div class="container section">
  <h2 class="indigo-text text-darken-4 center">Add / Remove Games</h2>
  <%= form_for current_user, url: update_user_games_path do |f| %>
    <h4 class="indigo-text text-darke-4">Game List</h4>
    <% Game.all.each do |game| %>
      <p>
        <label>
          <input type="checkbox" name="user[game_ids][]" value="<%= game.id %>" <%= 'checked' if @games.include?(game) %>>
          <span><%= game.name %></span>
        </label>
      </p>
    <% end %>
    <div class="input-field">
      <input type="submit" value="Add / Remove Games" class="btn">
    </div>
  <% end %>
</div>

app/views/games/index.html.erb
<div class="container section">
  <h2 class="indigo-text text-darken-4 center">Games</h2>
  <div class="row">
    <% @games.each do |game| %>
      <div class="col s6">
        <div class="card black white-text">
          <div class="card-image">
            <img src="<%= image_url(game.image_url) %>" class="image-responsive">
          </div>
          <div class="card-content content-box">
            <span class="card-title"><%= game.name %></span>
            <p><%= game.description %></p>
          </div>
          <div class="card-action center">
            <%= link_to "VISIT", game.url, target: :_blank %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/games/user_games.html.erb
<div class="container section">
  <h2 class="indigo-text text-darken-4 center">My Games</h2>
  <h4 class="center"><%= link_to "Add / Remove Games In Your List", edit_user_games_path %></h4>
  <div class="row">
    <% @games.each do |game| %>
      <div class="col s6">
        <div class="card black white-text">
          <div class="card-image">
            <img src="<%= image_url(game.image_url) %>" class="image-responsive">
          </div>
           <div class="card-content content-box">
            <span class="card-title"><%= game.name %></span>
            <p><%= game.description %></p>
          </div>
          <div class="card-action center">
            <%= link_to "Classes", game_classes_path(game.slug) %>
            <%= link_to "Questing", "#" %>
            <%= link_to "Dungeons", "#" %>
            <%= link_to "Crafting", "#" %>
            <%= link_to "Locations", "#" %>
            <%= link_to "Official Site", game.url, target: :_blank %>
         </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/klasses/index.html.erb
<div class="container section">
  <h2 class="indigo-text text-darken-4 center"><%= @game.name %> Classes</h2>
  <hr/>
  <div class="row">
    <ul class="tabs">
      <li class="tab col s12 m2 l2 offset-m2 offset-l1"><a href="#tanks" class="teal-text">Tanks</a></li>
      <li class="tab col s12 m2 l2"><a href="#healers" class="teal-text">Healers</a></li>
      <li class="tab col s12 m2 l2"><a href="#melee" class="teal-text">Melee</a></li>
      <li class="tab col s12 m2 l2"><a href="#ranged" class="teal-text">Ranged</a></li>
      <li class="tab col s12 m2 l2"><a href="#casters" class="teal-text">Casters</a></li>
    </ul>
  </div>
  <div class="row section tab-contents" id="tanks">
    <h4 class="indigo-text text-darken-4 center">Tanks</h4>
    <% @game.klasses.tanks.each do |klass| %>
      <div class="col s12 m6 l4">
        <div class="card black white-text">
          <div class="card-image">
            <img src="<%= image_url(klass.image_url) %>" class="image-responsive">
          </div>
          <div class="card-content content-box">
            <span class="card-title"><%= klass.name %> - <%= klass.role %></span>
            <p><%= klass.description %></p>
          </div>
          <div class="card-action center">
            <%= link_to "VISIT", "#" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="row section" id="healers">
    <h4 class="indigo-text text-darken-4 center">Healers</h4>
    <% @game.klasses.healers.each do |klass| %>
      <div class="col s12 m6 l4">
        <div class="card black white-text">
          <div class="card-image">
            <img src="<%= image_url(klass.image_url) %>" class="image-responsive">
          </div>
          <div class="card-content content-box">
            <span class="card-title"><%= klass.name %> - <%= klass.role %></span>
            <p><%= klass.description %></p>
          </div>
          <div class="card-action center">
            <%= link_to "VISIT", "#" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="row section" id="melee">
    <h4 class="indigo-text text-darken-4 center">Melee</h4>
    <% @game.klasses.melee.each do |klass| %>
      <div class="col s12 m6 l4">
        <div class="card black white-text">
          <div class="card-image">
            <img src="<%= image_url(klass.image_url) %>" class="image-responsive">
          </div>
          <div class="card-content content-box">
            <span class="card-title"><%= klass.name %> - <%= klass.role %></span>
            <p><%= klass.description %></p>
          </div>
          <div class="card-action center">
            <%= link_to "VISIT", "#" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="row section" id="ranged">
    <h4 class="indigo-text text-darken-4 center">Ranged</h4>
    <% @game.klasses.ranged.each do |klass| %>
      <div class="col s12 m6 l4">
        <div class="card black white-text">
          <div class="card-image">
            <img src="<%= image_url(klass.image_url) %>" class="image-responsive">
          </div>
          <div class="card-content content-box">
            <span class="card-title"><%= klass.name %> - <%= klass.role %></span>
            <p><%= klass.description %></p>
          </div>
          <div class="card-action center">
            <%= link_to "VISIT", "#" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="row section" id="casters">
    <h4 class="indigo-text text-darken-4 center">Casters</h4>
    <% @game.klasses.casters.each do |klass| %>
      <div class="col s12 m6 l4">
        <div class="card black white-text">
          <div class="card-image">
            <img src="<%= image_url(klass.image_url) %>" class="image-responsive">
          </div>
          <div class="card-content content-box">
            <span class="card-title"><%= klass.name %> - <%= klass.role %></span>
            <p><%= klass.description %></p>
          </div>
          <div class="card-action center">
            <%= link_to "VISIT", "#" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<script>
  $(document).ready(function(){
    $('.tabs').tabs({swipeable: true, onShow: resizeTab});
    
    $( window ).resize(function() { resizeTab(); });
  });
</script>

app/views/layouts/_footer.html.erb
<footer class="page-footer indigo darken-4">
  <div class="container">
    <h5>About</h5>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit dolorem alias in quaerat quae asperiores, ullam accusantium eos itaque molestias temporibus vero quia hic, libero, veritatis obcaecati saepe eligendi placeat?</p>
  </div>
  <div class="footer-copyright">
    <div class="container">
      <span class="right">© 2018 Game Todos</span>
    </div>
  </div>
</footer>

app/views/layouts/_logged_in_links.html.erb
<li><%= link_to "My Games", user_games_path %></li>
<li><%= link_to "Log Out", destroy_user_session_path, method: "delete" %></li>
<li><%= link_to "EG", "#", class: "btn-floating blue center" %></li>

app/views/layouts/_logged_out_links.html.erb
<li><%= link_to "Sign Up", new_user_registration_path %></li>
<li><%= link_to "Log In", new_user_session_path %></li>

app/views/layouts/_nav.html.erb
<nav class="nav-wrapper indigo darken-4">
  <div class="container">
    <%= link_to "Game Guides", root_path, class: "brand-logo" %>
    <ul class="right hide-on-med-and-down">
      <li><%= link_to "Games", games_path %></li>
      <% if user_signed_in? %>
        <%= render partial: 'layouts/logged_in_links' %>
      <% else %>
        <%= render partial: 'layouts/logged_out_links' %>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Game Guides</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/nav' %>
    <%= yield %>
    <%= render partial: 'layouts/footer' %>
  </body>
</html>

app/views/welcome/index.html.erb
<div class="container section">
  <h2 class="indigo-text text-darken-4 center">Welcome to Game Guides</h2>
  <h5 class="grey-text text-darken-2 center">Keep Track Of All Your Game Activities</h5>

  <section class="section" id="information">
    <div class="card blue darken-4">
      <div class="card-content white-text">
        <span class="card-title">Easily Setup your own Quest Chains</span>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum quasi voluptatibus exercitationem recusandae magni fugit aliquid nisi quos tenetur necessitatibus deleniti nostrum, veritatis odit modi ab porro doloribus consequatur asperiores.</p>
      </div>
    </div>

    <div class="card blue darken-4">
      <div class="card-content white-text">
        <span class="card-title">Keep track of items you a gathering</span>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum quasi voluptatibus exercitationem recusandae magni fugit aliquid nisi quos tenetur necessitatibus deleniti nostrum, veritatis odit modi ab porro doloribus consequatur asperiores.</p>
      </div>
    </div>

    <div class="card blue darken-4">
      <div class="card-content white-text">
        <span class="card-title">Crafting Item Cheat Sheet</span>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum quasi voluptatibus exercitationem recusandae magni fugit aliquid nisi quos tenetur necessitatibus deleniti nostrum, veritatis odit modi ab porro doloribus consequatur asperiores.</p>
      </div>
    </div>
  </section>
</div>